message:
  start: |
    –ú–Ω–æ–≥–æ—Å—Ç—Ä–æ—á–Ω–æ–µ
    —Å–æ–æ–±—â–µ–Ω–∏–µ,
    *–∫–æ—Ç–æ—Ä–æ–µ* –ø–æ–¥–¥–µ—Ä–∂–∏–≤–∞–µ—Ç _Markdown_
    –ü—É–ø—É–ø—É
    *–ø—É–ø—É–ø—É*
    
    _Long live @maksuslik_
  email: –£–∫–∞–∂–∏—Ç–µ —ç–ª–µ–∫—Ç—Ä–æ–Ω–Ω—É—é –ø–æ—á—Ç—É –ø–æ–ª—É—á–∞—Ç–µ–ª—è —Å–æ–æ–±—â–µ–Ω–∏—è
  incorrect_email: –£–∫–∞–∑–∞–Ω –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–π –∞–¥—Ä–µ—Å —ç–ª–µ–∫—Ç—Ä–æ–Ω–Ω–æ–π –ø–æ—á—Ç—ã!
  email_accept: |
    –ü–æ–ª—É—á–∞—Ç–µ–ª—å: %s
    –¢–µ–º–∞: %s
    %s
  email_received: |
    ‚úçÔ∏è –ù–æ–≤–æ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ –æ—Ç %s
    üìã –¢–µ–º–∞: %s
    %s